### ISSUE TITLE
Great comments

### ISSUE THREAD

**Issue by ghost** [jgoodsill/prj-rev-bwfs-dasmoto#1]
Great comments here
https://github.com/jgoodsill/prj-rev-bwfs-dasmoto/blob/7d6ca1632650066c6f546d919b700eb08fc7c9a5/Dasmoto's%20Arts%20%26%20Crafts/index.html#L30

**Comment by jgoodsill** [comment]
Thank you.  I wonder if these comments brand me as a newb.  I rarely see html comments when looking at pro sites.
